# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='level',
            field=models.CharField(default='normal', max_length=10),
        ),
    ]
